site_name: MSBA 511
site_url: https://dcyoung23.github.io/msba511/
repo_url: https://github.com/dcyoung23/msba511
repo_name: MSBA 511
nav:
  - Home: index.md
  - Syllabus: syllabus.md
  - Notes:
    - Week 1 - Intro / Association Rules: notes/week_1.md
    - Week 2 - Cluster Analysis: notes/week_2.md
    - Week 3 - k-Nearest Neighbors: notes/week_3.md
    - Week 4 - Collaborative Filtering: notes/week_4.md
    - Week 5 - Decision Trees: notes/week_5.md
    - Week 6 - Evaluating Classifiers: notes/week_6.md
    - Week 8 - Naive Bayes: notes/week_8.md
    #- Week 9 - Logistic Regression: notes/week_9.md
    #- Week 10 - Ensembles: notes/week_10.md
    #- Week 12 - Text Mining: notes/week_12.md
  - Resources:
    - Python:
      - Command Line Cheatsheet: resources/python/cl_cheatsheet.md
    - Tutorials:
      - Decision Trees: resources/tutorials/05_decision_trees_tutorial.ipynb
      - Evaluating Classifiers: resources/tutorials/06_evaluating_classifiers_tutorial.ipynb
      - Naive Bayes: resources/tutorials/08_naive_bayes_tutorial.ipynb
    - Chapter Code Examples:
      - Chapter 5: resources/textbook/ch5_code_examples.ipynb
      - Chapter 7: resources/textbook/ch7_code_examples.ipynb
      - Chapter 8: resources/textbook/ch8_code_examples.ipynb
      - Chapter 9: resources/textbook/ch9_code_examples.ipynb
      #- Chapter 10: resources/textbook/ch10_code_examples.ipynb
      #- Chapter 13: resources/textbook/ch13_code_examples.ipynb
      #- Chapter 14: resources/textbook/ch14_code_examples.ipynb
      - Chapter 15: resources/textbook/ch15_code_examples.ipynb
      - Chapter 16: resources/textbook/ch16_code_examples.ipynb
      #- Chapter 20: resources/textbook/ch20_code_examples.ipynb
theme:
  name: material
  logo: assets/images/logo.png
  favicon: assets/images/favicon.png
  font:
    text: Roboto
  icon:
    repo: fontawesome/brands/github
    admonition:
      note: fontawesome/solid/note-sticky
      tip: fontawesome/solid/lightbulb
  features:
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - header.autohide
    - announce.dismiss
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.integrate
  palette:
    - scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/weather-night
        name: Switch to light mode
    - scheme: default
      primary: blue
      accent: deep orange
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
      
markdown_extensions:
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
  - attr_list
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra:
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/dcyoung23
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/dcyoung23/
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@Professor-Young
    - icon: fontawesome/brands/creative-commons
      link: https://creativecommons.org/licenses/by-nc-sa/4.0/
      name: CC BY-NC-SA 4.0
  fontawesome:
    version: 6.0.0
  copyright: >
    Unless otherwise noted, the materials on this website and repository are freely available under the
    <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/" target="_blank" rel="noopener">Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License</a>.
  version:
    provider: mike

extra_css:
  - css/extra.css

watch:
  - src

plugins:
  - search
  - macros:
      module_name: src/main
  - open-in-new-tab
  - mkdocs-jupyter:
      execute: false