site_name: MSBA 511, Spring 2025
site_url: https://dcyoung23.github.io/msba511/
nav:
  - Home: index.md
  - Syllabus: syllabus.md
  - Calendar: calendar.md
  - Notes:
    - Week 1 - Intro / Association Rules: notes/week_1.md
  - Canvas: http://canvas.sandiego.edu/
  - Gradescope: https://www.gradescope.com/
theme:
  name: material
  font:
    text: Roboto
  features:
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - header.autohide
    - announce.dismiss
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.integrate
  palette:
    - scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/weather-night
        name: Switch to light mode
    - scheme: default
      primary: blue
      accent: deep orange
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

markdown_extensions:
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.superfences

  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

extra_css:
  - css/extra.css
