site_name: MSBA 511, Spring 2025
site_url: https://dcyoung23.github.io/msba511/
repo_url: https://github.com/dcyoung23/msba511
repo_name: MSBA 511
nav:
  - Home: index.md
  - Syllabus: syllabus.md
  - Calendar: calendar.md
  - Notes:
    - Week 1 - Intro / Association Rules: notes/week_1.md
    - Week 2 - Collaborative Filtering: notes/week_2.md
    - Week 3 - Cluster Analysis: notes/week_3.md
    - Week 4 - Classification / Decision Trees: notes/week_4.md
    - Week 5 - Evaluating Classifiers: notes/week_5.md
    - Week 6 - Exam 1: notes/week_6.md
    - Week 7 - k-Nearest Neighbors: notes/week_7.md
    - Week 8 - Naive Bayes: notes/week_8.md
    - Week 9 - Logistic Regression: notes/week_9.md
    - Week 10 - Ensembles: notes/week_10.md
    - Week 12 - Text Mining: notes/week_12.md
  - Resources:
    - Python:
      - Command Line Cheatsheet: resources/python/cl_cheatsheet.md
    - Chapter Code Examples:
      - Chapter 5: resources/textbook/ch5_code_examples.md
      - Chapter 7: resources/textbook/ch7_code_examples.md
      - Chapter 8: resources/textbook/ch8_code_examples.md
      - Chapter 9: resources/textbook/ch9_code_examples.md
      - Chapter 10: resources/textbook/ch10_code_examples.md
      - Chapter 13: resources/textbook/ch13_code_examples.md
      - Chapter 14: resources/textbook/ch14_code_examples.md
      - Chapter 15: resources/textbook/ch15_code_examples.md
      - Chapter 20: resources/textbook/ch20_code_examples.md
  - Links: links.md
theme:
  name: material
  font:
    text: Roboto
  icon:
    repo: fontawesome/brands/github
  features:
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - header.autohide
    - announce.dismiss
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.integrate
  palette:
    - scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/weather-night
        name: Switch to light mode
    - scheme: default
      primary: blue
      accent: deep orange
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

markdown_extensions:
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.superfences

  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

extra:
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/dcyoung23
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/dcyoung23/
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@Professor-Young
extra_css:
  - css/extra.css
