<h1><span style="color:#4472c4">MSBA 511: Data Mining for Business Analytics</span></h1>

## Programming Assignment 1: Instacart Recommendations

In this assignment, you will be working with a smaller version of the opened-sourced Instacart 2017 dataset. You can read about the data [here](https://tech.instacart.com/3-million-instacart-orders-open-sourced-d40d29ead6f2). The objective is to use association rules mining and collaborative filtering methods to make product recommendations.

⚠️ **If you `Run All Cells` in this notebook, you will lose any sample expected output.** ⚠️

You can always refer back to the original notebook on GitHub if you lose the expected output to compare to your results. 

#### Import libraries

# Association Rules

## Step 1: Load and Prepare Data

In this step, you will load the data and prepare it for association rules mining. 

### Step 1a: Load Orders Data

**Display first 5 rows only.**

<h4 style="color:blue"> Write Your Code Below: </h4>

<h3 style="color:teal"> Expected Output: </h3>

order_id  product_id
0         1       49302
1         1       11109
2         1       10246
3         1       49683
4         1       43633

### Step 1b: Load Products Data

**Display first 5 rows only.**

<h4 style="color:blue"> Write Your Code Below: </h4>

<h3 style="color:teal"> Expected Output: </h3>

product_id                                       product_name  aisle_id  \
0           1                         Chocolate Sandwich Cookies        61   
1           2                                   All-Seasons Salt       104   
2           3               Robust Golden Unsweetened Oolong Tea        94   
3           4  Smart Ones Classic Favorites Mini Rigatoni Wit...        38   
4           5                          Green Chile Anytime Sauce         5   

   department_id  
0             19  
1             13  
2              7  
3              1  
4             13

### Step 1c: Transform Data 

**Merge `orders` and `products` and retain only the `order_id` and `product_name` columns in the final dataframe.**

<h4 style="color:blue"> Write Your Code Below: </h4>

<h3 style="color:teal"> Expected Output: </h3>

order_id                                   product_name
0         1                               Bulgarian Yogurt
1         1  Organic 4% Milk Fat Whole Milk Cottage Cheese
2         1                          Organic Celery Hearts
3         1                                 Cucumber Kirby
4         1           Lightly Smoked Sardines in Olive Oil

**Transform data so products for each order are on one line in a comma separated list.**

<h4 style="color:blue"> Write Your Code Below: </h4>

<h3 style="color:teal"> Expected Output: </h3>

order_id                                       product_name
0         1  [Bulgarian Yogurt, Organic 4% Milk Fat Whole M...
1        36  [Grated Pecorino Romano Cheese, Spring Water, ...
2        38  [Shelled Pistachios, Organic Biologique Limes,...
3        96  [Roasted Turkey, Organic Cucumber, Organic Gra...
4        98  [Natural Spring Water, Organic Orange Juice Wi...

**Create array for products and display first 2 orders.**

<h4 style="color:blue"> Write Your Code Below: </h4>

<h3 style="color:teal"> Expected Output: </h3>

[['Bulgarian Yogurt',
  'Organic 4% Milk Fat Whole Milk Cottage Cheese',
  'Organic Celery Hearts',
  'Cucumber Kirby',
  'Lightly Smoked Sardines in Olive Oil',
  'Bag of Organic Bananas',
  'Organic Hass Avocado',
  'Organic Whole String Cheese'],
 ['Grated Pecorino Romano Cheese',
  'Spring Water',
  'Organic Half & Half',
  'Super Greens Salad',
  'Cage Free Extra Large Grade AA Eggs',
  'Prosciutto, Americano',
  'Organic Garnet Sweet Potato (Yam)',
  'Asparagus']]

### Step 1d: Create Sparse DataFrame

**Display the summary info of the dataframe for the output.**

<b>IMPORTANT</b>: Although this is a smaller version of the original Instacart data, this is still a real database with many products, some of which have very few orders. You need use ❗caution❗ on the dtypes that you use for your dataframe as it could consume a large amount of memory and crash your system! Also, mlxtend’s Apriori procedure will throw a ⚠️ warning ⚠️ message if you pass in non-boolean dtypes.

<h4 style="color:blue"> Write Your Code Below: </h4>

<h3 style="color:teal"> Expected Output: </h3>

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 47608 entries, 0 to 47607
Columns: 30403 entries, #2 Coffee Filters to with a Splash of Pineapple Coconut Water
dtypes: Sparse[bool, False](30403)
memory usage: 2.4 MB


**Next, display first 5 rows only to view a sample of the DataFrame.**

<h4 style="color:blue"> Write Your Code Below: </h4>

<h3 style="color:teal"> Expected Output: </h3>

#2 Coffee Filters  #4 Natural Brown Coffee Filters  \
0              False                            False   
1              False                            False   
2              False                            False   
3              False                            False   
4              False                            False   

   & Go! Hazelnut Spread + Pretzel Sticks  \
0                                   False   
1                                   False   
2                                   False   
3                                   False   
4                                   False   

   0 Calorie Fuji Apple Pear Water Beverage  \
0                                     False   
1                                     False   
2                                     False   
3                                     False   
4                                     False   

   0% Fat Black Cherry Greek Yogurt y  0% Fat Blueberry Greek Yogurt  \
0                               False                          False   
1                               False                          False   
2                               False                          False   
3                               False                          False   
4                               False                          False   

   0% Fat Free Organic Milk  0% Fat Greek Yogurt Black Cherry on the Bottom  \
0                     False                                           False   
1                     False                                           False   
2                     False                                           False   
3                     False                                           False   
4                     False                                           False   

   0% Fat Organic Greek Vanilla Yogurt  0% Fat Peach Greek Yogurt  ...  \
0                                False                      False  ...   
1                                False                      False  ...   
2                                False                      False  ...   
3                                False                      False  ...   
4                                False                      False  ...   

   with Olive Oil Mayonnaise  with Olive Oil Mayonnaise Dressing  \
0                      False                               False   
1                      False                               False   
2                      False                               False   
3                      False                               False   
4                      False                               False   

   with Sweet & Smoky BBQ Sauce Cheeseburger Sliders  \
0                                              False   
1                                              False   
2                                              False   
3                                              False   
4                                              False   

   with Xylitol Cinnamon 18 Sticks Sugar Free Gum  \
0                                           False   
1                                           False   
2                                           False   
3                                           False   
4                                           False   

   with Xylitol Minty Sweet Twist 18 Sticks Sugar Free Gum  \
0                                              False         
1                                              False         
2                                              False         
3                                              False         
4                                              False         

   with Xylitol Original Flavor 18 Sticks Sugar Free Gum  \
0                                              False       
1                                              False       
2                                              False       
3                                              False       
4              

## Step 2: Selecting Strong Rules

For this assignment, you are not given a predefined minimum support (`min_sup`) and  minimum confidence (`min_conf`) thresholds. **Instead, you are expected to analyze the dataset, explore different values, and determine an appropriate threshold based on the context of the data.**

### Step 2a: Create Frequent Itemsets

**Display all frequent itemsets.**

<h4 style="color:blue"> Write Your Code Below: </h4>

<h3 style="color:teal"> Example Output: </h3>

support                                      itemsets
0    0.015985                      (100% Whole Wheat Bread)
1    0.012036                         (2% Reduced Fat Milk)
2    0.016258                    (Apple Honeycrisp Organic)
3    0.029932                                   (Asparagus)
4    0.116892                      (Bag of Organic Bananas)
..        ...                                           ...
113  0.010460                (Organic Avocado, Large Lemon)
114  0.010754       (Organic Avocado, Organic Baby Spinach)
115  0.011763  (Organic Baby Spinach, Organic Strawberries)
116  0.011721  (Organic Hass Avocado, Organic Strawberries)
117  0.011910   (Organic Raspberries, Organic Strawberries)

[118 rows x 2 columns]

**Justify your minimum support (`min_sup`) threshold choice and explain why it makes the most sense for this scenario.**

<h4 style="color:purple"> Write Your Free-Form Response Below: </h4>

### Step 2b: Identify Strong Rules

A minimum confidence (`min_conf`) is not specified. Determine an appropriate threshold based on the context of the data. Justify your choice and explain why it makes the most sense for this scenario.

**Display strong association rules and only include the `antecedents`, `consequents`, `support`, `confidence`, and `lift` columns.**

ℹ️The example output below does **not** include all rules that exceed the specified threshold and is provided as an example only.

<h4 style="color:blue"> Write Your Code Below: </h4>

<h3 style="color:teal"> Example Output: </h3>

antecedents               consequents   support  confidence  \
10                   (Limes)             (Large Lemon)  0.012183    0.266177   
12     (Organic Raspberries)    (Organic Strawberries)  0.011910    0.286364   
2      (Organic Raspberries)  (Bag of Organic Bananas)  0.013758    0.330808   
1     (Organic Hass Avocado)  (Bag of Organic Bananas)  0.018190    0.324709   
11    (Organic Hass Avocado)    (Organic Strawberries)  0.011721    0.209224   
3   (Bag of Organic Bananas)    (Organic Strawberries)  0.023567    0.201617   

        lift  
10  4.324970  
12  3.513711  
2   2.830029  
1   2.777855  
11  2.567198  
3   2.473864

**Justify your minimum confidence (`min_conf`) threshold choice and explain why it makes the most sense for this scenario.**

<h4 style="color:purple"> Write Your Free-Form Response Below: </h4>

# Collaborative Filtering

## Step 3: Conduct Item-Based Collaborative Filtering

In the Collaborative Filtering demo, we conducted a User-Based approach to recommend courses offered by The Institute for Statistics Education at Statistics.com based on user ratings. In this dataset, we could assume that every transaction is a different customer and treat the index as a customer id. We would have `47,608` customers and `30,403` products that would require similarity analysis and could be computationally expensive. Therefore, we are going to conduct Item-Based Collaborative Filtering and find similar items and recommend the most popular items among the similar products for one specific customer (identified by the index value).

**Important**: This final step will require some independent thought and research since we did not specifically cover Item-based collaborative filtering for a binary purchase matrix in the demo and there isn't a code example in the textbook.

### Step 3a: Calculate Pairwise Cosine Similarities

**Create a sparse row matrix for the cosine similarities for all products (`30,403`).**

Check out the SciPy documentation for `sparse.csr_matrix`[here](https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.csr_matrix.html). You may find using the intermediate data output from the transaction encoder from **Step 1** helpful. 

⚠️Think carefully how the data will need to be transformed prior to calculating the pairwise cosine similaries.

<h4 style="color:blue"> Write Your Code Below: </h4>

<h3 style="color:teal"> Expected Output: </h3>

Similarities Shape:
 (30403, 30403)

Pairwise Cosine Similarities Output:
 [[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 1.]
 [0. 0. 0. ... 0. 1. 1.]]



### Step 3b: Convert Similarities to a Dataframe

⚠️You may want to use a datatype of **float32** for the binary matrix to reduce the memory usage of the dataframe.

**Display first 5 rows only.**

<h4 style="color:blue"> Write Your Code Below: </h4>

<h3 style="color:teal"> Expected Output: </h3>

#2 Coffee Filters  \
#2 Coffee Filters                                       1.0   
#4 Natural Brown Coffee Filters                         0.0   
& Go! Hazelnut Spread + Pretzel Sticks                  0.0   
0 Calorie Fuji Apple Pear Water Beverage                0.0   
0% Fat Black Cherry Greek Yogurt y                      0.0   

                                          #4 Natural Brown Coffee Filters  \
#2 Coffee Filters                                                     0.0   
#4 Natural Brown Coffee Filters                                       1.0   
& Go! Hazelnut Spread + Pretzel Sticks                                0.0   
0 Calorie Fuji Apple Pear Water Beverage                              0.0   
0% Fat Black Cherry Greek Yogurt y                                    0.0   

                                          & Go! Hazelnut Spread + Pretzel Sticks  \
#2 Coffee Filters                                                            0.0   
#4 Natural Brown Coffee Filters                                              0.0   
& Go! Hazelnut Spread + Pretzel Sticks                                       1.0   
0 Calorie Fuji Apple Pear Water Beverage                                     0.0   
0% Fat Black Cherry Greek Yogurt y                                           0.0   

                                          0 Calorie Fuji Apple Pear Water Beverage  \
#2 Coffee Filters                                                              0.0   
#4 Natural Brown Coffee Filters                                                0.0   
& Go! Hazelnut Spread + Pretzel Sticks                                         0.0   
0 Calorie Fuji Apple Pear Water Beverage                                       1.0   
0% Fat Black Cherry Greek Yogurt y                                             0.0   

                                          0% Fat Black Cherry Greek Yogurt y  \
#2 Coffee Filters                                                        0.0   
#4 Natural Brown Coffee Filters                                          0.0   
& Go! Hazelnut Spread + Pretzel Sticks                                   0.0   
0 Calorie Fuji Apple Pear Water Beverage                                 0.0   
0% Fat Black Cherry Greek Yogurt y                                       1.0   

                                          0% Fat Blueberry Greek Yogurt  \
#2 Coffee Filters                                                   0.0   
#4 Natural Brown Coffee Filters                                     0.0   
& Go! Hazelnut Spread + Pretzel Sticks                              0.0   
0 Calorie Fuji Apple Pear Water Beverage                            0.0   
0% Fat Black Cherry Greek Yogurt y                                  0.0   

                                          0% Fat Free Organic Milk  \
#2 Coffee Filters                                              0.0   
#4 Natural Brown Coffee Filters                                0.0   
& Go! Hazelnut Spread + Pretzel Sticks                         0.0   
0 Calorie Fuji Apple Pear Water Beverage                       0.0   
0% Fat Black Cherry Greek Yogurt y                             0.0   

                                          0% Fat Greek Yogurt Black Cherry on the Bottom  \
#2 Coffee Filters                                                                    0.0   
#4 Natural Brown Coffee Filters                                                      0.0   
& Go! Hazelnut Spread + Pretzel Sticks                                               0.0   
0 Calorie Fuji Apple Pear Water Beverage                                             0.0   
0% Fat Black Cherry Greek Yogurt y                                                   0.0   

                                          0% Fat Organic Greek Vanilla Yogurt  \
#2 Coffee Filters                                                         0.0   
#4 Natural Brown Coffee Filters                                           0.0   
& Go! Hazelnut Spread + Pretz

### Step 3c: Display Top 10 Products for a Specific Product

**First, let's review item-to-item similaries and show the top 10 products for `Organic Hass Avocado`.**

<h4 style="color:blue"> Write Your Code Below: </h4>

<h3 style="color:teal"> Expected Output: </h3>

Top 10 Similar Products for: Organic Hass Avocado


Bag of Organic Bananas                  0.224788
Organic Strawberries                    0.173463
Organic Raspberries                     0.165363
Organic Lemon                           0.157154
Organic Cucumber                        0.147154
Organic Baby Spinach                    0.146428
Organic Yellow Onion                    0.129458
Organic Garlic                          0.128459
Organic Large Extra Fancy Fuji Apple    0.117539
Limes                                   0.114490
Name: Organic Hass Avocado, dtype: float32

### Step 3d: Item Specific Recommendation

**Recommend to a shopper the top 5 related products based on the last product added to the cart.**

We can simulate a current shopper's cart by picking one transaction from the existing data. Customer **45713** (index value = 45713 from original `sparse_df`) has added **5 products** to the cart so far. We do not know the order the products were placed in the cart so for the sake of this assignment, we will just assume the last product based on the column index which happens to be in **alpha** order. **This recommendation will simply be an item-to-item recommendation and does not consider neighbours for this customer.**

⚠️ **No Expected Output** is provided for the **intermediate step** that shows the products in the customers cart! ⚠️

It is up to you to produce code that filters the original data for index **45713** to identify the last product for your recommendations.

ℹ️ You should only have **5** products in the cart!

<h4 style="color:blue"> Write Your Code Below: </h4>

<h3 style="color:teal"> Expected Output: </h3>

Top 5 Similar Products for the Last Product Added:


Bag of Organic Bananas    0.241460
Organic Raspberries       0.204567
Organic Hass Avocado      0.173463
Organic Blueberries       0.158631
Organic Baby Spinach      0.150741
dtype: float32

### Step 3e: Nearest Neighbor Recommendations

**Make product recommendations based on the shopper's cart.**

ℹ️ There are over **30,000** products in the dataset. You might want to consider limiting the products that you include in your purchases data to run through the KNNBasic algorithm.

⚠️ You will most likely **NOT** be able to conduct `'user_based': True` recommendations due to space requirements to run the algorithm! ⚠️

**Prepare the purchases dataframe for model training.**

<h4 style="color:blue"> Write Your Code Below: </h4>

<h3 style="color:teal"> Sample Output: </h3>

<class 'pandas.core.frame.DataFrame'>
Index: 1428240 entries, 0 to 1428239
Data columns (total 3 columns):
 #   Column    Non-Null Count    Dtype 
---  ------    --------------    ----- 
 0   customer  1428240 non-null  int64 
 1   product   1428240 non-null  object
 2   purchase  1428240 non-null  int8  
dtypes: int64(1), int8(1), object(1)
memory usage: 34.1+ MB


**Train model and make predictions for all customers and for products included in your purchases data.**

<h4 style="color:blue"> Write Your Code Below: </h4>

<h3 style="color:teal"> Sample Output: </h3>

Computing the cosine similarity matrix...
Done computing similarity matrix.


Large Lemon     Limes  Organic Gala Apples  Organic Navel Orange  \
0     0.064036  0.075985             0.089327              0.093363   
1     0.000000  0.000000             0.000000              0.000000   
2     0.000000  0.000000             0.000000              0.000000   
3     0.101196  0.084677             0.098107              0.094625   
4     0.105681  0.105941             0.108560              0.110414   

   Organic Strawberries  Bag of Organic Bananas  Organic Raspberries  \
0              0.113832                0.292944             0.116686   
1              0.000000                0.000000             0.000000   
2              0.000000                0.000000             0.000000   
3              0.134894                0.129351             0.346929   
4              0.143139                0.316771             0.357418   

   Organic Hass Avocado  Organic Blueberries  Organic Baby Spinach  ...  \
0              0.324560             0.083691              0.093130  ...   
1              0.000000             0.000000              0.000000  ...   
2              0.000000             0.000000              0.000000  ...   
3              0.123211             0.412321              0.115853  ...   
4              0.156521             0.120266              0.130401  ...   

   Organic Red Bell Pepper  Organic Blackberries  Organic Whole String Cheese  \
0                 0.080117              0.064099                     0.430092   
1                 0.000000              0.000000                     0.000000   
2                 0.000000              0.000000                     0.000000   
3                 0.113447              0.124804                     0.089865   
4                 0.128605              0.102234                     0.110173   

   Organic D'Anjou Pears  Organic Lemon  Organic Granny Smith Apple  \
0               0.088300       0.113934                    0.084010   
1               0.000000       0.000000                    0.000000   
2               0.000000       0.000000                    0.000000   
3               0.094581       0.101731                    0.099742   
4               0.110095       0.139119                    0.111423   

   Organic Yellow Onion  Organic Small Bunch Celery  Original Hummus  \
0              0.092130                    0.081121         0.086766   
1              0.000000                    0.000000         0.000000   
2              0.000000                    0.000000         0.000000   
3              0.096432                    0.100419         0.084410   
4              0.404637                    0.130416         0.092444   

   Honeycrisp Apple  
0          0.066395  
1          0.000000  
2          0.000000  
3          0.087123  
4          0.088782  

[5 rows x 30 columns]

**Top 5 Recommendations for Customer 45713**

ℹ️ No Sample Output is provided for this step! 

⚠️ Be sure to only include products the customer has not already added to their cart!

<h4 style="color:blue"> Write Your Code Below: </h4>

## Step 4: Compare Methods and Discuss Implications

To wrap up this assignment, go back and review the `rules` from Step 2 where the `antecedent` is a single itemset for the last product added to the cart for this customer. 

1. Discuss the pros and cons of using strong association rules vs. an item-based collaborative filtering approach to make recommendations for the customer.
2. Did you observe any differences in your recommendations for customer 45713 between the top 5 item-to-item similarities vs. the nearest neighbour item-based recommendations?

<h4 style="color:purple"> Write Your Free-Form Response Below: </h4>